# 101 NumPy Exercises for Data Analysis (Python)

The goal of the numpy exercises is to serve as a reference as well as to get you to apply numpy beyond the basics. The questions are of 4 levels of difficulties with L1 being the easiest to L4 being the hardest.

[Exercices here.](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### 1. Import numpy as np and see the version

In [2]:
import numpy as np

print(np.__version__)

2.2.4


### 2. How to create a 1D array ?

Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output:

```python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [3]:
arr_1d = np.arange(0,10)

print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


### 3. How to create a boolean array?

Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

A. I decided to use the `np.full` function

[https://www.w3resource.com/numpy/array-creation/full.php#google_vignette]

In [4]:
shape = (3, 3)
value = True
arr = np.full(shape, value, dtype=np.bool)

print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 4. How to extract items that satisfy a given condition from 1D array?

Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired output:

```python
#> array([1, 3, 5, 7, 9])
```

https://wesmckinney.com/book/numpy-basics#ndarray_boolean

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = arr[arr % 2 != 0]

print(arr)

[1 3 5 7 9]


### 5. How to replace items that satisfy a condition with another value in numpy array?

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:

```python
#>  array([ 0, -1,  2, -1,  4, -1,  6,
```

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 6. How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:

```python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
```

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = arr.copy()

out[out % 2 != 0] = -1

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


The actual solution was expecting me to use `np.where`

https://numpy.org/doc/2.2/reference/generated/numpy.where.html

In [8]:
out = np.where(arr % 2 == 1, -1, arr)

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### 6. How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:

```python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 
```

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where(arr % 2 == 1, -1, arr)

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### 7. How to reshape an array?

Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

```python
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:

```python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [10]:
arr = np.arange(10)

np.reshape(arr, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

```python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:

```python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

Answer reference: https://www.w3schools.com/python/numpy/numpy_array_join.asp

In [13]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

arr = np.vstack((a,b))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 9. How to stack two arrays horizontally?

Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

```python
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:

```shell
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

arr = np.concatenate((a,b), axis=1)

print(arr)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### 10. How to generate custom sequences in numpy without hardcoding?

Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

```python
a = np.array([1,2,3])
```

Desired Output:

```shell
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
a = np.array([1,2,3])

b = np.concatenate((a, a, a))

AxisError: axis 1 is out of bounds for array of dimension 1